### ISSUE TITLE
DVR

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_android#5]
### Tasks
- [ ] Distinguir Live com DVR
- [ ] Determinar duração
- [ ] Determinar currentTime
- [ ] Permitir seek programático
- [ ] Permitir seek pela UI
- [ ] Configurar UI
- [ ] Testes
